/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_soondori_log_ardoinotoandroid_MainActivity */

#ifndef _Included_com_soondori_log_ardoinotoandroid_MainActivity
#define _Included_com_soondori_log_ardoinotoandroid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_soondori_log_ardoinotoandroid_MainActivity
 * Method:    makeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_soondori_log_ardoinotoandroid_MainActivity_makeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
